# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_image_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_caption',
        ),
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
    ]
