# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 08:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0007_auto_20181220_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='liked_image',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='who_liked',
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
